/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as tuttoIndexRouteImport } from './routes/(tutto)/index'

const tuttoIndexRoute = tuttoIndexRouteImport.update({
  id: '/(tutto)/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof tuttoIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof tuttoIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/(tutto)/': typeof tuttoIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/'
  fileRoutesByTo: FileRoutesByTo
  to: '/'
  id: '__root__' | '/(tutto)/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  tuttoIndexRoute: typeof tuttoIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/(tutto)/': {
      id: '/(tutto)/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof tuttoIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  tuttoIndexRoute: tuttoIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
