/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as tuttoIndexRouteImport } from './routes/(tutto)/index'
import { Route as tuttoSpielRouteImport } from './routes/(tutto)/spiel'

const tuttoIndexRoute = tuttoIndexRouteImport.update({
  id: '/(tutto)/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const tuttoSpielRoute = tuttoSpielRouteImport.update({
  id: '/(tutto)/spiel',
  path: '/spiel',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/spiel': typeof tuttoSpielRoute
  '/': typeof tuttoIndexRoute
}
export interface FileRoutesByTo {
  '/spiel': typeof tuttoSpielRoute
  '/': typeof tuttoIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/(tutto)/spiel': typeof tuttoSpielRoute
  '/(tutto)/': typeof tuttoIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/spiel' | '/'
  fileRoutesByTo: FileRoutesByTo
  to: '/spiel' | '/'
  id: '__root__' | '/(tutto)/spiel' | '/(tutto)/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  tuttoSpielRoute: typeof tuttoSpielRoute
  tuttoIndexRoute: typeof tuttoIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/(tutto)/': {
      id: '/(tutto)/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof tuttoIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(tutto)/spiel': {
      id: '/(tutto)/spiel'
      path: '/spiel'
      fullPath: '/spiel'
      preLoaderRoute: typeof tuttoSpielRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  tuttoSpielRoute: tuttoSpielRoute,
  tuttoIndexRoute: tuttoIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
